spring.application.name=resernur-api
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/resernur-db
spring.datasource.username=postgres
spring.datasource.password=root
swagger.base-path=/**
springdoc.swagger-ui.path=/api/docs
api.version=1.0.0

server.port=5000
app.public-url=http://localhost:5000
frontend.port=5173

security.jwt.secret=ULTRAGAYSECRETFORPROYECTODETALLERVOHYEAHMYFUCKINGGODTHISSHITMUSTBEEVENLONGERTHANTHIS
security.jwt.expiration=3600000

app.cors.allowed-origins=*

media.files.path=C:/Users/IOs/Desktop/SEM1-2026/TallerV/Proyecto Sistema de Reservas de Espacios/resernur_media/files
media.images.path=C:/Users/IOs/Desktop/SEM1-2026/TallerV/Proyecto Sistema de Reservas de Espacios/resernur_media/images
media.endpoint=media