spring.application.name=resernur-api
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/resernur-db
spring.datasource.username=postgres
spring.datasource.password=postgres
swagger.base-path=/**
springdoc.swagger-ui.path=/api/docs
api.version=1.0.0

server.port=5000
frontend.port=5173

security.jwt.secret=ULTRAGAYSECRETFORPROYECTODETALLERVOHYEAH
security.jwt.expiration=3600000

app.cors.allowed-origins=*